/* build-data.mjs — compile the JSON source-of-truth files into a single
   window.EM_DATA bundle (assets/data.js) so pages work when opened from
   file:// (no fetch/CORS). Mirrors the ctobs catalog.js convention.
   Run: node scripts/build-data.mjs */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

const activities = {};
const actDir = join(root, 'data', 'activities');
for (const f of readdirSync(actDir).filter(f => f.endsWith('.json'))) {
  const rec = readJson(join(actDir, f));
  activities[rec.id] = rec;
}

const standards = {};
const stdDir = join(root, 'data', 'standards');
for (const f of readdirSync(stdDir).filter(f => f.endsWith('.json'))) {
  standards[basename(f, '.json')] = readJson(join(stdDir, f));
}

const maps = readJson(join(root, 'data', 'maps.json'));

const bundle = { activities, standards, maps };
const out = '/* GENERATED by scripts/build-data.mjs — do not edit by hand.\n' +
  '   Source of truth: data/activities/*.json, data/standards/*.json, data/maps.json */\n' +
  'window.EM_DATA = ' + JSON.stringify(bundle, null, 2) + ';\n';

writeFileSync(join(root, 'assets', 'data.js'), out);
console.log('build-data: wrote assets/data.js —',
  Object.keys(activities).length, 'activities,',
  Object.keys(standards).length, 'standards files,',
  maps.maps.length, 'map types.');
