#!/usr/bin/env node
/* ============================================================
   build-i18n.js — SST area language dictionaries.
   ------------------------------------------------------------
   Three pages in this area speak seven languages through the
   shared engine in assets/i18n.js:

     _i18n/<lang>.json         -> i18n-sst.js         (area landing)
     acesst/_i18n/<lang>.json  -> acesst/i18n-acesst.js (ACE tickets)
                               -> acesst/i18n-acesst-about.js (about page)

   The landing dictionary is flat: key -> string.

   The ACE file has three sections, because the area has three
   kinds of text:

     "ui"      flat chrome and control strings, registered with
               BreakoutI18n so data-i18n attributes and t() pick
               them up.
     "about"   the long-form about page, registered separately as
               "acesst-about" so neither page carries the other's
               payload.
     "tickets" the 28 tickets themselves, keyed by ticket id.
               These are not chrome — they are content the app
               renders — so they go out as window.ACE_TX[lang]
               and the app re-reads them on
               breakout-i18n:changed. English lives inline in
               index.html and is the fallback for any ticket a
               translation has not covered, so a missing entry
               degrades to English rather than to a blank card.

   Run after editing any _i18n JSON:  node build-i18n.js
   ============================================================ */
const fs = require('fs'), path = require('path');
const ROOT = __dirname, LANGS = ['en', 'es', 'vi', 'ar', 'hi', 'ur', 'zh'];

function read(dir, lang) {
  const fp = path.join(dir, lang + '.json');
  return fs.existsSync(fp) ? JSON.parse(fs.readFileSync(fp, 'utf8')) : null;
}

/* ---- area landing page ---- */
const hub = {};
for (const l of LANGS) { const d = read(path.join(ROOT, '_i18n'), l); if (d) hub[l] = d; }
fs.writeFileSync(path.join(ROOT, 'i18n-sst.js'),
  '/* Auto-generated by build-i18n.js — SST landing page dictionary. */\n' +
  'BreakoutI18n.register("sst-hub", ' + JSON.stringify(hub) + ');\n');

/* ---- ACE the SST ---- */
const ui = {}, tx = {}, about = {};
for (const l of LANGS) {
  const d = read(path.join(ROOT, 'acesst', '_i18n'), l);
  if (!d) continue;
  ui[l] = d.ui || {};
  if (d.about && Object.keys(d.about).length) about[l] = d.about;
  if (d.tickets && Object.keys(d.tickets).length) tx[l] = d.tickets;
}
fs.writeFileSync(path.join(ROOT, 'acesst', 'i18n-acesst.js'),
  '/* Auto-generated by build-i18n.js — ACE the SST dictionary. */\n' +
  'window.ACE_TX = ' + JSON.stringify(tx) + ';\n' +
  'BreakoutI18n.register("acesst", ' + JSON.stringify(ui) + ');\n');

/* The about page is long-form prose and shares nothing with the ticket
   app, so it gets its own file rather than making every visitor to the
   tool download an essay, or every reader of the essay download 28
   translated tickets. */
fs.writeFileSync(path.join(ROOT, 'acesst', 'i18n-acesst-about.js'),
  '/* Auto-generated by build-i18n.js — About ACE the SST dictionary. */\n' +
  'BreakoutI18n.register("acesst-about", ' + JSON.stringify(about) + ');\n');

const counts = LANGS.map(l => l + ':' + (tx[l] ? Object.keys(tx[l]).length : 0)).join(' ');
console.log('build-i18n: landing [' + Object.keys(hub).join(', ') + ']');
console.log('build-i18n: acesst  ui [' + Object.keys(ui).join(', ') + '] · translated tickets ' + counts);
console.log('build-i18n: about   [' + Object.keys(about).join(', ') + ']');
