/* PlotPoint — The Picture of Dorian Gray. Generated by _build_cchs_dorian.js. */
window.__ROOM__ = {
  "id": "doriangray",
  "storageKey": "plotpoint.doriangray.v1",
  "ui": {
    "skip": "Skip to the activity",
    "brand.tag": "Read · Reason · Play",
    "reset": "Reset",
    "reset.confirm": "Reset this room and clear saved progress on this device?",
    "footer.tagline": "No logins · no accounts · no data collected · runs entirely in your browser.",
    "footer.privacy": "Privacy & compliance",
    "footer.back": "All PlotPoint rooms",
    "review.flag": "Needs review",
    "progress.chip": "{n}/{total} activities done",
    "nav.enter": "Enter the Story",
    "nav.vocab": "Vocabulary",
    "nav.relic": "Relic Room",
    "nav.ctob": "Crack the Case",
    "nav.arcade": "Arcade Game",
    "nav.analysis": "Analyze the Text",
    "nav.extend": "Extend the Idea",
    "nav.genai": "Gen AI Partner",
    "nav.print": "Print Materials",
    "nav.teacher": "Teacher Guide",
    "nav.done": "completed",
    "enter.eyebrow": "Enter the Story",
    "enter.by": "by {a}",
    "enter.spoiler": "Spoiler level",
    "enter.access": "Text access",
    "enter.copyright": "Copyright",
    "enter.contentReview": "Content-review note",
    "enter.contentDefault": "Districts should review edition, maturity level, local policy, instructional purpose, student needs, and community expectations.",
    "enter.goals": "Learning goals",
    "enter.stages": "When to use this room",
    "enter.stage.before": "Before reading",
    "enter.stage.during": "During reading",
    "enter.stage.after": "After reading",
    "enter.aceEyebrow": "Thinking routine",
    "enter.ace": "The ACE Framework",
    "enter.aceIntro": "Every task in this room asks you to Articulate, Connect, and Extend your thinking.",
    "enter.readListen": "Read & Listen — free",
    "enter.readListenTitle": "Get the full text and audio",
    "enter.readListenNote": "This book is in the public domain. These free, external resources open in a new tab — verify the link and edition before assigning.",
    "enter.read": "Read the full text (Project Gutenberg)",
    "enter.listen": "Listen — audiobook (LibriVox)",
    "enter.readAloud": "Prefer a read-aloud? Students may also use their device's built-in read-aloud or a district-approved AI tool on the public-domain text.",
    "ace.articulate": "A · Articulate",
    "ace.connect": "C · Connect",
    "ace.extend": "E · Extend",
    "vocab.eyebrow": "Build Your Vocabulary",
    "vocab.title": "Words for The Picture of Dorian Gray",
    "vocab.intro": "{n} terms that unlock the novel. Study them, match them, then test them in context.",
    "vocab.mode.study": "Study cards",
    "vocab.mode.match": "Matching",
    "vocab.mode.context": "Context clues",
    "vocab.example": "Example",
    "vocab.nonexample": "Nonexample",
    "vocab.matchHint": "Select a term, then select its meaning. Correct pairs lock in.",
    "vocab.terms": "Terms",
    "vocab.defs": "Meanings",
    "vocab.matchDone": "All terms matched. Nicely reasoned.",
    "vocab.contextLabel": "Choose the word that fits",
    "vocab.noContext": "Context sentences are coming soon for this room.",
    "relic.eyebrow": "Explore the Relic Room",
    "relic.title": "The Locked Portrait Gallery",
    "relic.reviewed": "Reviewed",
    "relic.investigate": "Investigate",
    "relic.placeholder": "Image placeholder",
    "relic.artifact": "Artifact {n}",
    "relic.q.identify": "Identify it — what is this document or object?",
    "relic.q.purpose": "Explain its likely purpose",
    "relic.q.significance": "Its literary significance",
    "relic.check": "Check my investigation",
    "relic.answerAll": "Answer all three questions before checking.",
    "relic.scored": "You reasoned {c} of {m} correct. Read the reveal, then respond.",
    "relic.reveals": "What it reveals",
    "relic.conceals": "What it may conceal",
    "relic.aceLabel": "ACE response",
    "relic.aceDefault": "Articulate what this artifact shows, connect it to a theme, and extend it to a question it raises.",
    "relic.acePlaceholder": "Write your ACE response (stays on this device)…",
    "ctob.eyebrow": "Crack the Case",
    "ctob.title": "The Case of the Unaging Face",
    "ctob.progress": "{n} of {total} locks opened",
    "ctob.done": "Every lock is open. The case is solved — with evidence.",
    "ctob.lock": "Lock {n}",
    "lock.digit": "Number lock",
    "lock.word": "Word lock",
    "lock.mc": "Choice lock",
    "lock.sequence": "Sequence lock",
    "ctob.correct": "Open — the evidence supports it.",
    "ctob.enter": "Enter your answer",
    "ctob.check": "Check",
    "ctob.wrong": "Not yet — re-read the evidence and try again.",
    "ctob.hint": "Show a hint",
    "seq.up": "Move up",
    "seq.down": "Move down",
    "arcade.eyebrow": "Play the Arcade Game",
    "arcade.title": "Public Image or Hidden Cost?",
    "arcade.default": "Sort each card into the reading it best supports.",
    "arcade.drophere": "Drop cards here — or use the buttons on each card.",
    "arcade.moveto": "Move to {b}",
    "arcade.placedn": "{n} of {total} cards sorted",
    "arcade.check": "Check my reasoning",
    "arcade.replay": "Play again",
    "arcade.placeAll": "Sort every card before checking.",
    "arcade.result": "{c} of {total} sorted with sound reasoning.",
    "arcade.cards": "Sources to weigh",
    "arcade.followup": "Discuss / write",
    "analysis.eyebrow": "Analyze the Text",
    "analysis.title": "Literary Analysis",
    "analysis.intro": "Five evidence questions, then written responses. Every question rewards the best-supported reading.",
    "analysis.mc": "Question {n}",
    "analysis.check": "Check my answers",
    "analysis.answerAll": "Answer all five questions first.",
    "analysis.score": "{c} of {total} best-supported answers.",
    "analysis.written": "Written responses",
    "analysis.writtenIntro": "These stay on your device. Print them from the Print Materials tab.",
    "analysis.short": "Short response {n}",
    "analysis.paragraph": "Evidence paragraph",
    "analysis.aceReflection": "ACE reflection",
    "analysis.localNote": "Your writing is never sent anywhere — it stays in this browser.",
    "extend.eyebrow": "Extend the Idea",
    "extend.title": "Tell It in Documents",
    "extend.format": "Format",
    "extend.evidence": "The epistolary technique I am building on",
    "extend.transfers": "What transfers to my modern account",
    "extend.changes": "What changes with modern documents",
    "extend.breaks": "Where the comparison stops working",
    "extend.response": "My found-document account",
    "extend.localNote": "Your response stays on this device. You own it.",
    "genai.eyebrow": "Gen AI Thinking Partner",
    "genai.title": "Optional Gen AI Support",
    "genai.rule": "Think first. Use Gen AI after effort, not before it. Never let Gen AI replace your reasoning.",
    "genai.enable": "Teacher: enable Gen AI supports on this device",
    "genai.enableNote": "Off by default. This setting is stored only in this browser and is never transmitted.",
    "genai.warning": "Never paste names, private information, or another person's writing. Use only district-approved tools.",
    "genai.prompts": "Copyable prompts",
    "genai.copy": "Copy",
    "genai.copied": "Copied ✓",
    "genai.receipt": "Gen AI Thinking Receipt",
    "genai.receiptIntro": "If you use Gen AI, complete this receipt so your reasoning stays yours. It stays on this device.",
    "genai.before": "Before Gen AI",
    "genai.during": "Gen AI interaction",
    "genai.after": "After Gen AI",
    "r.first": "1. My first explanation",
    "r.evidence": "2. My initial evidence",
    "r.question": "3. My unanswered question",
    "r.asked": "4. What I asked",
    "r.suggested": "5. What the tool suggested",
    "r.accepted": "6. What I accepted",
    "r.changed": "7. What I changed",
    "r.rejected": "8. What I rejected",
    "r.why": "9. Why I made those choices",
    "r.textEvidence": "10. My evidence from the text",
    "r.final": "11. My final ACE response",
    "genai.altTitle": "Non-AI alternative",
    "genai.alt": "Prefer no AI? Trade receipts with a partner and interview each other with the same questions, or use the printed thinking sheet.",
    "print.eyebrow": "Print Student Materials",
    "print.title": "Printable Packet",
    "print.intro": "Print a no-login paper packet for this room. Use your browser's print dialog to save as PDF.",
    "print.item.vocab": "Vocabulary reference",
    "print.item.relic": "Relic Room evidence sheet",
    "print.item.ctob": "Breakout evidence sheet",
    "print.item.analysis": "Analysis questions",
    "print.item.extend": "Found-document organizer",
    "print.item.ace": "ACE organizer",
    "print.item.receipt": "Gen AI thinking receipt",
    "print.button": "Print / Save as PDF",
    "print.answer": "Answer:",
    "teacher.eyebrow": "Teacher Guide",
    "teacher.title": "For the Educator",
    "teacher.pathways": "Assignment pathways",
    "teacher.standards": "Standards & supports",
    "teacher.standardsNote": "This room is aligned to — not reproduced from — the standards below. Confirm codes against your current adoption.",
    "teacher.framework": "Framework",
    "teacher.codes": "Alignment",
    "teacher.answerKeys": "Answer keys (educator reference)",
    "teacher.answerNote": "These are provided for teachers. Assign the student tabs before revealing keys.",
    "teacher.reviewItems": "Items to verify before teaching",
    "path.quick": "Quick Play",
    "path.quick.time": "15–25 minutes",
    "path.quick.body": "Vocabulary preview, arcade game, five-question check, one Articulate response.",
    "path.invest": "Investigation",
    "path.invest.time": "30–45 minutes",
    "path.invest.body": "Relic Room, evidence organizer, one Connect response, optional discussion.",
    "path.complete": "Complete Case",
    "path.complete.time": "60–90 minutes / multiple periods",
    "path.complete.body": "Vocabulary, Relic Room, breakout, arcade, analysis, extend task, ACE reflection."
  },
  "content": {
    "meta": {
      "title": "The Picture of Dorian Gray",
      "author": "Oscar Wilde",
      "grades": "Grades 11–12",
      "genre": "Gothic philosophical novel",
      "time": "60–90 minutes",
      "spoiler": "Full spoilers",
      "rights": "Public domain",
      "textAccess": "The 1890 and 1891 forms are public domain. The linked Project Gutenberg edition is the revised 1891 novel; teachers should confirm that it matches the assigned edition.",
      "copyright": "Oscar Wilde’s novel is public domain in the United States. Modern introductions, annotations, and adaptations may still be copyrighted.",
      "contentNote": "The novel includes murder, suicide, drug use, blackmail, exploitation, anti-Semitic stereotypes, and coded sexuality. Preview the assigned edition and follow local policy.",
      "gutenberg": "https://www.gutenberg.org/ebooks/174",
      "audio": "https://librivox.org/the-picture-of-dorian-gray-by-oscar-wilde/",
      "hero": "images/hero.webp",
      "heroAlt": "An original instructional illustration: a handsome Victorian gentleman before a veiled portrait in a shadowed London room, with the painted face beginning to age."
    },
    "hook": "Dorian Gray sees Basil Hallward’s portrait of him and wishes that the painted image—not his own face—would bear the marks of age and experience. The wish appears to come true. Guided by Lord Henry’s glittering philosophy of sensation, Dorian protects a flawless public image while the hidden portrait records cruelty, corruption, fear, and guilt. Wilde’s Gothic novel asks whether beauty can be separated from ethics, whether influence excuses choice, and whether art reveals or conceals the self.",
    "goals": [
      "Trace how the portrait externalizes Dorian’s conscience and changes after decisive choices.",
      "Analyze the contrast among Basil’s moral concern, Lord Henry’s epigrams, and Dorian’s actions.",
      "Explain how dramatic irony separates Dorian’s reputation from what the reader knows.",
      "Evaluate the novel’s competing claims about beauty, influence, responsibility, and reform."
    ],
    "stages": {
      "before": [
        "Preview aestheticism, Gothic doubling, and the difference between the 1890 and 1891 editions.",
        "Discuss whether a public image can become a substitute for character."
      ],
      "during": [
        "Track every change in the portrait alongside the choice that precedes it.",
        "Distinguish Lord Henry’s provocative claims from the consequences produced by Dorian’s actions."
      ],
      "after": [
        "Use the relic room and case locks to reconstruct the chain of responsibility.",
        "Complete the analysis and transfer task using evidence from the assigned edition."
      ]
    },
    "ace": {
      "articulate": {
        "goal": "Explain one idea in your own words.",
        "prompt": "Explain how the portrait functions as more than a supernatural object."
      },
      "connect": {
        "goal": "Show how ideas fit together.",
        "prompt": "Connect one of Lord Henry’s claims to a later choice Dorian makes and its consequence."
      },
      "extend": {
        "goal": "Apply the learning.",
        "prompt": "Apply the novel’s public-image/private-self conflict to a modern context, noting where the comparison breaks down."
      }
    },
    "vocab": [
      {
        "term": "aestheticism",
        "def": "a movement emphasizing beauty and artistic experience",
        "example": "judging an object chiefly by its beauty",
        "nonexample": "treating beauty as irrelevant",
        "context": "In the novel, aestheticism helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "epigram",
        "def": "a brief, polished statement with a surprising turn",
        "example": "one of Lord Henry’s memorable reversals",
        "nonexample": "a long plot summary",
        "context": "In the novel, epigram helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "hedonism",
        "def": "the view that pleasure is a central good",
        "example": "Dorian’s pursuit of sensation",
        "nonexample": "accepting hardship for a moral duty",
        "context": "In the novel, hedonism helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "decadence",
        "def": "luxurious self-indulgence associated with decline",
        "example": "Dorian’s increasingly secret life",
        "nonexample": "disciplined simplicity",
        "context": "In the novel, decadence helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "double",
        "def": "a character or image that reflects a divided self",
        "example": "the portrait as Dorian’s moral double",
        "nonexample": "an unrelated background figure",
        "context": "In the novel, double helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "dramatic irony",
        "def": "a gap between what the audience knows and what characters know",
        "example": "society praises Dorian while readers know his secret",
        "nonexample": "every character sharing the same facts",
        "context": "In the novel, dramatic irony helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "influence",
        "def": "the power to shape another person’s ideas or behavior",
        "example": "Lord Henry shaping Dorian’s outlook",
        "nonexample": "physical force that removes all choice",
        "context": "In the novel, influence helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "conscience",
        "def": "the inward sense that judges right and wrong",
        "example": "the portrait making guilt visible",
        "nonexample": "public applause alone",
        "context": "In the novel, conscience helps explain the gap between appearance, choice, and consequence."
      },
      {
        "term": "reputation",
        "def": "the judgment others hold about a person",
        "example": "Dorian’s preserved social image",
        "nonexample": "the full truth of private conduct",
        "context": "In the novel, reputation helps explain the gap between appearance, choice, and consequence."
      }
    ],
    "relic": {
      "name": "The Locked Portrait Gallery",
      "intro": "Seven original instructional reconstructions of objects and places from the novel. They are teaching images, not illustrations from any edition.",
      "artifacts": [
        {
          "id": "portrait",
          "name": "The Changing Portrait",
          "image": "images/portrait.webp",
          "clues": [
            "A full-length portrait Basil Hallward paints of Dorian Gray.",
            "It records the age and moral damage that Dorian’s unchanged face conceals.",
            "The divided self: public beauty versus private consequence."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "A full-length portrait Basil Hallward paints of Dorian Gray.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "It records the age and moral damage that Dorian’s unchanged face conceals.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "The divided self: public beauty versus private consequence.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "The divided self: public beauty versus private consequence.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what the changing portrait shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "studio",
          "name": "Basil’s Studio",
          "image": "images/studio.webp",
          "clues": [
            "The flower-filled London studio where Basil completes the portrait and Lord Henry first influences Dorian.",
            "It is the origin point of both the artwork and Dorian’s wish to remain young.",
            "Art can reveal a truth that conversation and appearance hide."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "The flower-filled London studio where Basil completes the portrait and Lord Henry first influences Dorian.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "It is the origin point of both the artwork and Dorian’s wish to remain young.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "Art can reveal a truth that conversation and appearance hide.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "Art can reveal a truth that conversation and appearance hide.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what basil’s studio shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "theater",
          "name": "The Theater Program",
          "image": "images/theater.webp",
          "clues": [
            "A reminder of Sibyl Vane’s performances and Dorian’s infatuation with her acting.",
            "When love makes performance feel false to Sibyl, Dorian values the lost illusion more than the person.",
            "Aesthetic worship can erase another person’s humanity."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "A reminder of Sibyl Vane’s performances and Dorian’s infatuation with her acting.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "When love makes performance feel false to Sibyl, Dorian values the lost illusion more than the person.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "Aesthetic worship can erase another person’s humanity.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "Aesthetic worship can erase another person’s humanity.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what the theater program shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "yellowbook",
          "name": "The Yellow Book",
          "image": "images/yellowbook.webp",
          "clues": [
            "A decadent French novel Lord Henry gives Dorian after Sibyl’s death.",
            "Dorian treats it as a script for sensation, collecting experiences while avoiding responsibility.",
            "Influence matters, but influence does not remove personal choice."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "A decadent French novel Lord Henry gives Dorian after Sibyl’s death.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "Dorian treats it as a script for sensation, collecting experiences while avoiding responsibility.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "Influence matters, but influence does not remove personal choice.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "Influence matters, but influence does not remove personal choice.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what the yellow book shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "schoolroom",
          "name": "The Locked Schoolroom",
          "image": "images/schoolroom.webp",
          "clues": [
            "The upstairs room where Dorian hides the portrait from every visitor.",
            "Its secrecy lets him separate his spotless reputation from the evidence of his conduct.",
            "Concealment protects an image while deepening isolation and fear."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "The upstairs room where Dorian hides the portrait from every visitor.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "Its secrecy lets him separate his spotless reputation from the evidence of his conduct.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "Concealment protects an image while deepening isolation and fear.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "Concealment protects an image while deepening isolation and fear.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what the locked schoolroom shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "letter",
          "name": "Basil’s Unfinished Letter",
          "image": "images/letter.webp",
          "clues": [
            "Basil plans to leave for Paris but first confronts Dorian about destructive rumors.",
            "The confrontation leads Dorian to show Basil the portrait and then murder him.",
            "The demand to face evidence becomes dangerous when reputation matters more than repentance."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "Basil plans to leave for Paris but first confronts Dorian about destructive rumors.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "The confrontation leads Dorian to show Basil the portrait and then murder him.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "The demand to face evidence becomes dangerous when reputation matters more than repentance.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "The demand to face evidence becomes dangerous when reputation matters more than repentance.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what basil’s unfinished letter shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        },
        {
          "id": "knife",
          "name": "The Knife Before the Portrait",
          "image": "images/knife.webp",
          "clues": [
            "The weapon Dorian turns against the portrait near the novel’s end.",
            "He tries to destroy the record of conscience instead of accepting responsibility.",
            "Destroying evidence cannot undo the self that created it."
          ],
          "identify": {
            "q": "Which description best identifies this artifact?",
            "choices": [
              "The weapon Dorian turns against the portrait near the novel’s end.",
              "An unrelated object with no role in Dorian’s choices",
              "A public award Dorian receives for charity",
              "A document that proves Lord Henry committed Dorian’s actions"
            ]
          },
          "purpose": {
            "q": "What role does it play in the novel?",
            "choices": [
              "He tries to destroy the record of conscience instead of accepting responsibility.",
              "It resolves every conflict immediately",
              "It proves appearance always reveals character",
              "It removes Dorian’s responsibility for his choices"
            ]
          },
          "significance": {
            "q": "What larger idea does it help develop?",
            "choices": [
              "Destroying evidence cannot undo the self that created it.",
              "Beauty guarantees moral goodness",
              "Art has no connection to life",
              "Consequences disappear when no one sees them"
            ]
          },
          "reveals": "Destroying evidence cannot undo the self that created it.",
          "conceals": "What the object cannot settle without careful attention to Dorian’s choices and their effects on other people.",
          "ace": "Articulate what the knife before the portrait shows; connect it to Dorian’s divided identity; extend the idea to a modern conflict between image and accountability."
        }
      ]
    },
    "ctob": {
      "name": "The Case of the Unaging Face",
      "intro": "Open six evidence locks by reconstructing the novel’s causal chain.",
      "locks": [
        {
          "type": "word",
          "prompt": "Who paints Dorian’s portrait? (surname)",
          "evidence": [
            "He is an artist.",
            "He admires Dorian and worries about Lord Henry’s influence."
          ],
          "hints": [
            "His first name is Basil.",
            "The surname begins Hall…",
            "The answer is Hallward."
          ],
          "answer": "hallward"
        },
        {
          "type": "mc",
          "prompt": "Why does the portrait become central to Dorian’s conflict?",
          "options": [
            "It visibly bears the age and damage his own face escapes.",
            "It makes Basil famous and ends the story happily.",
            "It proves Lord Henry controls the supernatural event.",
            "It is displayed publicly throughout the novel."
          ],
          "hints": [
            "Compare the painted face with Dorian’s public appearance."
          ]
        },
        {
          "type": "sequence",
          "prompt": "Order these turning points from earliest to latest.",
          "items": [
            "Dorian wishes the portrait would age instead of him.",
            "Dorian rejects Sibyl after her failed performance.",
            "Dorian shows Basil the changed portrait and kills him.",
            "Dorian stabs the portrait and dies."
          ],
          "hints": [
            "The wish begins the bargain.",
            "Sibyl comes before Basil’s final visit.",
            "The attempted destruction ends the sequence."
          ]
        },
        {
          "type": "word",
          "prompt": "What single word names the social image Dorian protects while hiding the portrait?",
          "evidence": [
            "Other people continue to see youth and charm.",
            "Rumors circulate, but his appearance shields him."
          ],
          "hints": [
            "It means what others think of someone.",
            "It begins rep…",
            "The answer is reputation."
          ],
          "answer": "reputation"
        },
        {
          "type": "mc",
          "prompt": "What does Basil’s confrontation demand from Dorian?",
          "options": [
            "That he face the moral meaning of the rumors and his influence on others.",
            "That he sell the portrait for money.",
            "That he travel with Lord Henry.",
            "That he deny art has any value."
          ],
          "hints": [
            "Basil is concerned about character, not price."
          ]
        },
        {
          "type": "mc",
          "prompt": "Why does Dorian’s final attack on the portrait fail as reform?",
          "options": [
            "He attacks the evidence of conscience rather than honestly accepting responsibility.",
            "The knife is too weak to cut canvas.",
            "Lord Henry secretly replaces the portrait.",
            "The portrait has never changed."
          ],
          "hints": [
            "Distinguish erasing evidence from repairing harm."
          ]
        }
      ]
    },
    "arcade": {
      "name": "Public Image or Hidden Cost?",
      "instruction": "Sort each statement by whether it belongs to Dorian’s admired public image or to the hidden consequences recorded by the portrait.",
      "buckets": [
        {
          "id": "image",
          "label": "Public image",
          "short": "Image"
        },
        {
          "id": "cost",
          "label": "Hidden cost",
          "short": "Cost"
        }
      ],
      "cards": [
        {
          "text": "Dorian’s face remains youthful while years pass.",
          "bucket": "image",
          "why": "Society reads beauty as evidence of innocence."
        },
        {
          "text": "Guests continue to find Dorian charming.",
          "bucket": "image",
          "why": "His social performance protects his standing."
        },
        {
          "text": "The portrait is locked away from visitors.",
          "bucket": "cost",
          "why": "The concealed canvas records what reputation omits."
        },
        {
          "text": "Sibyl dies after Dorian’s cruel rejection.",
          "bucket": "cost",
          "why": "Aesthetic disappointment has a human consequence."
        },
        {
          "text": "Basil is murdered after seeing the portrait.",
          "bucket": "cost",
          "why": "Dorian answers moral confrontation with violence."
        },
        {
          "text": "Rumors fail to overcome the evidence of Dorian’s appearance.",
          "bucket": "image",
          "why": "The novel dramatizes the persuasive power of surfaces."
        },
        {
          "text": "Alan Campbell is coerced into destroying evidence.",
          "bucket": "cost",
          "why": "Dorian extends his secrecy through blackmail and exploitation."
        },
        {
          "text": "Dorian’s attempted reform does not restore those he harmed.",
          "bucket": "cost",
          "why": "A single self-flattering act cannot erase a pattern of choices."
        }
      ],
      "followup": "Why does Wilde let society see one Dorian while the reader and portrait see another?"
    },
    "analysis": {
      "mcq": [
        {
          "q": "The portrait most strongly functions as —",
          "options": [
            "an external record of conscience and consequence.",
            "proof that beauty and goodness are identical.",
            "a neutral decoration with no structural role.",
            "evidence that Basil controls Dorian."
          ],
          "why": "an external record of conscience and consequence."
        },
        {
          "q": "Lord Henry’s role is best understood as —",
          "options": [
            "a powerful influence whose ideas tempt Dorian, without eliminating Dorian’s agency.",
            "the direct performer of every crime.",
            "a reliable moral guide endorsed by every consequence.",
            "a narrator who knows about the portrait."
          ],
          "why": "a powerful influence whose ideas tempt Dorian, without eliminating Dorian’s agency."
        },
        {
          "q": "Sibyl’s failed performance matters because —",
          "options": [
            "Dorian values the aesthetic illusion she created more than her full humanity.",
            "it proves she never loved acting.",
            "it causes Basil to destroy the portrait.",
            "it exposes Dorian’s secret to London."
          ],
          "why": "Dorian values the aesthetic illusion she created more than her full humanity."
        },
        {
          "q": "The locked room chiefly develops the theme of —",
          "options": [
            "secrecy dividing public reputation from private responsibility.",
            "education improving Dorian’s judgment.",
            "friendship repairing every harm.",
            "wealth guaranteeing safety."
          ],
          "why": "secrecy dividing public reputation from private responsibility."
        },
        {
          "q": "The ending most clearly rejects the belief that —",
          "options": [
            "a person can destroy the evidence of wrongdoing without confronting the self responsible for it.",
            "art can affect a viewer.",
            "choices produce consequences.",
            "reputation can mislead."
          ],
          "why": "a person can destroy the evidence of wrongdoing without confronting the self responsible for it."
        }
      ],
      "short": [
        "Compare Basil’s and Lord Henry’s ideas about what art should do. Which view does the plot complicate most?",
        "Choose one change in the portrait and explain the decision that causes it and the theme it develops."
      ],
      "paragraph": "How does Wilde use the gap between Dorian’s face and portrait to develop a claim about beauty and moral responsibility? Use a precise sequence of evidence.",
      "aceReflection": "Which interpretation changed as you connected Dorian’s choices to their consequences?"
    },
    "extend": {
      "name": "The Curated Self",
      "prompt": "Compare Dorian’s protected public image with a modern form of self-curation. Explain what transfers, what changes, and where the comparison breaks down.",
      "format": "An evidence-based comparison that keeps the novel’s supernatural mechanism distinct from modern technology."
    },
    "genaiPrompts": [
      {
        "title": "Articulate",
        "text": "Ask me questions that help me explain the portrait as a symbol without writing my answer."
      },
      {
        "title": "Connect",
        "text": "Challenge my connection between one of Lord Henry’s claims and a later consequence."
      },
      {
        "title": "Evidence",
        "text": "Check whether my evidence from The Picture of Dorian Gray supports my claim; do not rewrite it."
      },
      {
        "title": "Counterreading",
        "text": "Offer one plausible counterreading of Dorian’s responsibility and ask me to respond with evidence."
      },
      {
        "title": "Context",
        "text": "Help me distinguish aestheticism as a historical movement from Dorian’s individual choices."
      },
      {
        "title": "Critique",
        "text": "Identify unsupported assumptions in my analysis and respond only with questions."
      }
    ],
    "teacher": {
      "overview": "A public-domain, full-spoiler companion focused on Gothic doubling, aestheticism, dramatic irony, influence, agency, and responsibility.",
      "reviewNotes": [
        "Confirm whether the course uses the 1890 magazine text or Wilde’s revised 1891 book edition.",
        "Preview mature content, stereotypes, coded sexuality, murder, suicide, drug use, and blackmail.",
        "Verify all standards and translations locally before high-stakes use."
      ]
    },
    "standards": {
      "teks": "Aligned to English IV strands for response, multiple genres, author’s craft, composition, and inquiry. Confirm exact expectations. (Needs review)",
      "elps": "Supports listening, speaking, reading, and writing through visuals, structured talk, vocabulary, and evidence frames. (Needs review)",
      "ccss": "RL.11-12.1–6; W.11-12.1, 4, 9; SL.11-12.1. (Needs review)",
      "udl": "Multiple means of engagement, representation, and action/expression through visual artifacts, audio access, sorting, writing, and print."
    }
  }
};
