/* PlotPoint — the title collection (single source of truth for the hub).
   Each title is a standalone learning room. status: "live" (has href) or
   "planned" (coming soon, no link yet). Flip status + set href when a room ships.

   English base lives here; per-language card overrides (title stays in its
   published form; genre/desc/tags translate) live in plotpoint-i18n.js under
   __PLOTPOINT_TITLES__. Filter facet values below are STABLE KEYS — the hub
   translates them for display via the chrome dictionary (facet.* keys). */
window.PLOTPOINT_TITLES = [
  {
    id: "metamorphosis",
    title: "The Metamorphosis",
    author: "Franz Kafka",
    href: "metamorphosis/",
    status: "live",
    accent: "#7a4fce",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "novella"],
    time: "60-90",
    reading: ["after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Gregor's Room",
    ctob: "The Locked Door",
    arcade: "Routine Breakdown",
    desc: "Gregor Samsa wakes transformed. Investigate obligation, isolation, and identity through symbols, evidence, and the pressures of a changing family.",
  },
  {
    id: "myths",
    clt: true,
    title: "Selected Myths (Bulfinch)",
    author: "Thomas Bulfinch",
    href: "myths/",
    status: "live",
    accent: "#c9822b",
    grades: "6–9",
    gradeBand: "6-8",
    genre: ["mythology", "nonfiction"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["multi", "relational"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Museum of Lost Myths",
    ctob: "Who Stole the Fire?",
    arcade: "Hero's Path",
    desc: "Gods, quests, and archetypes. Match obstacles to transformations, recognize quest patterns, and transfer myth patterns to modern stories.",
  },
  {
    id: "aesop",
    clt: true,
    title: "Aesop's Fables (Selections)",
    author: "Aesop",
    href: "aesop/",
    status: "live",
    accent: "#a8792b",
    grades: "6–9",
    gradeBand: "6-8",
    genre: ["fables", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["multi", "relational"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Fable Cabinet",
    ctob: "The Moral of the Story",
    arcade: "Moral or Detail?",
    desc: "Tiny tales, big lessons. Identify the moral of each fable, tell a moral from a plot detail, and write your own.",
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    href: "dracula/",
    status: "live",
    accent: "#6b2a3a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "gothic", "horror"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Demeter Archive",
    ctob: "The Missing Ship Log",
    arcade: "Night Route",
    desc: "Reconstruct movement, sequence documents, evaluate narrators, connect setting and suspense, and analyze epistolary structure.",
  },
  {
    id: "butterflies",
    title: "In the Time of the Butterflies",
    author: "Julia Alvarez",
    href: "butterflies/",
    status: "live",
    accent: "#8c5a2b",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "historical-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Hidden Resistance Cache",
    ctob: "Code of the Butterflies",
    arcade: "History or Invention?",
    desc: "An independent companion to Alvarez's novel of the four Mirabal sisters — 'Las Mariposas' — who resisted the Trujillo dictatorship. Reproduces no text.",
  },
  {
    id: "annefrank",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    href: "annefrank/",
    status: "live",
    accent: "#7a5a6a",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["nonfiction", "memoir"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Secret Annex",
    ctob: "Behind the Bookcase",
    arcade: "Ordinary Life or Extraordinary Danger?",
    desc: "An independent companion to Anne Frank's diary of two years hiding from the Nazis in Amsterdam — an ordinary teenager and an extraordinary witness. Reproduces no text.",
  },
  {
    id: "separate",
    title: "Separate Is Never Equal",
    author: "Duncan Tonatiuh",
    href: "separate/",
    status: "live",
    accent: "#3f6b8c",
    grades: "4–7",
    gradeBand: "6-8",
    genre: ["nonfiction", "biography"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Schoolhouse Files",
    ctob: "The Case for the Schools",
    arcade: "Excuse or Truth?",
    desc: "An independent companion to the true story of Sylvia Mendez and her family's fight to end school segregation (Mendez v. Westminster, 1947). Reproduces no text.",
  },
  {
    id: "between",
    title: "Between the World and Me",
    author: "Ta-Nehisi Coates",
    href: "between/",
    status: "live",
    accent: "#4a3f5a",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["nonfiction", "memoir"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Letter to His Son",
    ctob: "The Weight of the Body",
    arcade: "The Dream or the Reckoning?",
    desc: "An independent companion to Coates's letter to his son on race, history, and the Black body in America — 'the body,' 'the Dream,' 'the Mecca.' Reproduces no text.",
  },
  {
    id: "poe",
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe",
    href: "poe/",
    status: "live",
    accent: "#6b2f3f",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "gothic", "horror"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Scene of the Crime",
    ctob: "Under the Floorboards",
    arcade: "Sanity or Madness?",
    desc: "Poe's classic of psychological horror: an unreliable narrator insists he is sane while confessing to murder — and a heartbeat only he can hear undoes him. Free text and audio.",
  },
  {
    id: "kindred",
    title: "Kindred",
    author: "Octavia E. Butler",
    href: "kindred/",
    status: "live",
    accent: "#5c4a7a",
    grades: "10–12",
    gradeBand: "9-12",
    genre: ["fiction", "historical-fiction", "science-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Family Archive",
    ctob: "The Broken Ledger",
    arcade: "Timeline Repair",
    desc: "Reconstruct chronology, analyze cause and effect, compare historical and fictional evidence, and examine perspective across time.",
  },
  {
    id: "bnw",
    title: "Brave New World",
    author: "Aldous Huxley",
    href: "bnw/",
    status: "live",
    accent: "#2f6f7a",
    grades: "10–12",
    gradeBand: "9-12",
    genre: ["fiction", "dystopian", "science-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The World State Systems Lab",
    ctob: "The Forbidden Book",
    arcade: "The Price of Stability",
    desc: "An independent companion to Huxley's dystopia of engineered happiness — castes, conditioning, soma, and the price of a 'stable' world. Reproduces no text.",
  },
  {
    id: "canterbury",
    clt: true,
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    href: "canterbury/",
    status: "live",
    accent: "#8c6a2b",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["fiction", "poetry", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Pilgrims' Luggage",
    ctob: "The Missing Tale",
    arcade: "Pilgrim Road",
    desc: "Match traveler and object, analyze motivation, identify satire, interpret social roles, and connect frame story and tale.",
  },

  // ── Philosophy sub-collection (public-domain, CLT-aligned) ──
  {
    id: "apology",
    clt: true,
    title: "The Apology",
    author: "Plato",
    href: "apology/",
    status: "live",
    accent: "#3f5aa6",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Trial of Socrates",
    ctob: "The Charges Against Socrates",
    arcade: "Argument or Appeal?",
    desc: "On trial for his life, Socrates defends the examined life. Reconstruct the charges, analyze his reasoning, and tell reasoned argument from appeals to pity.",
  },
  {
    id: "cave",
    clt: true,
    title: "The Allegory of the Cave",
    author: "Plato",
    href: "cave/",
    status: "live",
    accent: "#4a4a7a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Inside the Cave",
    ctob: "Shadows on the Wall",
    arcade: "Out of the Cave",
    desc: "Prisoners mistake shadows for reality. Trace Plato's allegory of ignorance, education, and the difficult climb toward the truth.",
  },
  {
    id: "meditations",
    clt: true,
    title: "Meditations",
    author: "Marcus Aurelius",
    href: "meditations/",
    status: "live",
    accent: "#6b5b3a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Emperor's Journal",
    ctob: "The Stoic's Notebook",
    arcade: "In Your Control?",
    desc: "A Roman emperor writes notes to himself on duty, self-control, and what is within our power. Explore the core ideas of Stoicism.",
  },
  {
    id: "enchiridion",
    clt: true,
    title: "The Enchiridion",
    author: "Epictetus",
    href: "enchiridion/",
    status: "live",
    accent: "#5a6b4a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Handbook",
    ctob: "What Is Up to Us",
    arcade: "Control or Let Go",
    desc: "A former slave's practical handbook of Stoic wisdom: focus on what you can control, and let go of what you cannot.",
  },
  {
    id: "ethics",
    clt: true,
    title: "Nicomachean Ethics (Selections)",
    author: "Aristotle",
    href: "ethics/",
    status: "live",
    accent: "#7a5a3a",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Workshop of Virtue",
    ctob: "Finding the Mean",
    arcade: "The Golden Mean",
    desc: "What is a good life? Aristotle argues that virtue is a habit and lies in the mean between extremes. Analyze his account of happiness and character.",
  },
  {
    id: "consolation",
    clt: true,
    title: "The Consolation of Philosophy",
    author: "Boethius",
    href: "consolation/",
    status: "live",
    accent: "#6a4a6a",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Prisoner's Cell",
    ctob: "The Wheel of Fortune",
    arcade: "Fortune's Wheel",
    desc: "Awaiting execution, Boethius is visited by Lady Philosophy. Examine fortune, fate, and where true happiness is found.",
  },
  {
    id: "confessions",
    clt: true,
    title: "Confessions (Selections)",
    author: "Augustine",
    href: "confessions/",
    status: "live",
    accent: "#8c5a2b",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Garden of Memory",
    ctob: "Take Up and Read",
    arcade: "Ordered Loves",
    desc: "A restless young man chases success, pleasure, and answers — and finds none enough. Trace Augustine's search, his conversion, and the restless heart.",
  },
  {
    id: "seneca",
    clt: true,
    title: "Letters from a Stoic (Selections)",
    author: "Seneca",
    href: "seneca/",
    status: "live",
    accent: "#4a6b6a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Letter Desk",
    ctob: "The Value of Time",
    arcade: "Reclaim the Day",
    desc: "A powerful Roman writes a friend about how to live: value your time, choose true friends, and stop fearing troubles that never come.",
  },
  {
    id: "douglass",
    clt: true,
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    href: "douglass/",
    status: "live",
    accent: "#3f5a6b",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["nonfiction", "memoir", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Path to Literacy",
    ctob: "The Pathway from Slavery to Freedom",
    arcade: "Chains and Keys",
    desc: "Born into slavery and forbidden to read, Douglass finds that literacy is 'the pathway from slavery to freedom.' A firsthand testimony and argument.",
  },
  {
    id: "federalist",
    clt: true,
    title: "The Federalist Papers (Selections)",
    author: "Publius (Hamilton, Madison, Jay)",
    href: "federalist/",
    status: "live",
    accent: "#4a5a8c",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["nonfiction", "philosophy", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Printer's Table",
    ctob: "The Ratification Debate",
    arcade: "Safeguard or Danger?",
    desc: "Three writers, one pen name, and a newspaper campaign to ratify the Constitution. Examine faction, the large republic, and checks and balances.",
  },
  {
    id: "cicero",
    clt: true,
    title: "On Friendship (Laelius de Amicitia)",
    author: "Marcus Tullius Cicero",
    href: "cicero/",
    status: "live",
    accent: "#7d5a3c",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "nonfiction", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Laelius's Study",
    ctob: "The Test of True Friendship",
    arcade: "True Friend or Flatterer?",
    desc: "An old Roman, grieving his dearest friend, asks what makes a friendship real — and how to tell a true friend from a flatterer. Virtue, loyalty, and honest counsel.",
  },
  {
    id: "utopia",
    clt: true,
    title: "Utopia",
    author: "Thomas More",
    href: "utopia/",
    status: "live",
    accent: "#2f7d6e",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["philosophy", "classic", "fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Traveler's Chest",
    ctob: "The Island of No Place",
    arcade: "Utopia or Europe?",
    desc: "A traveler describes an island with no private property, no money, and a six-hour workday. Its name means 'no place.' A 1516 satire that holds a mirror to Europe.",
  },
  {
    id: "ladytiger",
    title: "The Lady, or the Tiger?",
    author: "Frank R. Stockton",
    href: "ladytiger/",
    status: "live",
    accent: "#b5892b",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "short-story", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The King's Arena",
    ctob: "The Right-Hand Door",
    arcade: "The Lady or the Tiger?",
    desc: "Stockton's famous open-ended tale: a princess alone knows which door hides the tiger and which the lady — and the story ends before we learn what she chose. Free text and audio.",
  },
  {
    id: "ransom",
    title: "The Ransom of Red Chief",
    author: "O. Henry",
    href: "ransom/",
    status: "live",
    accent: "#b8642b",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "short-story", "humor"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Kidnappers' Hideout",
    ctob: "The Counter-Offer",
    arcade: "Plan vs. Reality",
    desc: "O. Henry's comic masterpiece of situational irony: two crooks kidnap a boy who is having far too much fun — until his father makes them an offer they never expected. Free text and audio.",
  },
  {
    id: "magi",
    title: "The Gift of the Magi",
    author: "O. Henry",
    href: "magi/",
    status: "live",
    accent: "#9c3a4a",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "short-story", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Della and Jim's Flat",
    ctob: "The Two Treasures",
    arcade: "Wise or Foolish?",
    desc: "O. Henry's beloved twist tale: a poor young couple each secretly sell their one treasure to buy the other a Christmas gift — and situational irony meets selfless love. Free text and audio.",
  },
  {
    id: "monkeyspaw",
    title: "The Monkey's Paw",
    author: "W. W. Jacobs",
    href: "monkeyspaw/",
    status: "live",
    accent: "#3f5044",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "short-story", "horror", "gothic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Whites' Parlour",
    ctob: "Three Wishes",
    arcade: "Wish or Consequence?",
    desc: "The classic horror tale of three wishes: a cursed talisman grants exactly what the Whites ask for — at a terrible price. A masterclass in foreshadowing and dread. Free text and audio.",
  },
  {
    id: "cask",
    title: "The Cask of Amontillado",
    author: "Edgar Allan Poe",
    href: "cask/",
    status: "live",
    accent: "#4a2f3a",
    grades: "8–11",
    gradeBand: "9-12",
    genre: ["fiction", "gothic", "horror", "short-story"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Montresor's Catacombs",
    ctob: "The Unfinished Toast",
    arcade: "Fortunato's View or the Reader's View?",
    desc: "Poe's masterpiece of revenge and dramatic irony: Montresor lures the proud Fortunato deep into the catacombs with the promise of a rare wine — and only one returns. Free text and audio.",
  },
  {
    id: "owlcreek",
    title: "An Occurrence at Owl Creek Bridge",
    author: "Ambrose Bierce",
    href: "owlcreek/",
    status: "live",
    accent: "#5a5240",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "short-story", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Bridge and the Vision",
    ctob: "The Falling Instant",
    arcade: "Real or Illusion?",
    desc: "Bierce's famous twist: a Civil War prisoner's daring escape from a hanging unfolds vividly — until the last line reveals it all happened in an instant. A study in point of view. Free text.",
  },
  {
    id: "bet",
    title: "The Bet",
    author: "Anton Chekhov",
    href: "bet/",
    status: "live",
    accent: "#4a5566",
    grades: "8–11",
    gradeBand: "9-12",
    genre: ["fiction", "short-story", "classic"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Garden Lodge",
    ctob: "The Final Night",
    arcade: "The Lawyer's Wisdom or the Banker's Greed?",
    desc: "Chekhov's philosophical wager: a lawyer bets fifteen years of solitary confinement against two million rubles — and years of reading change what he believes a life is worth. Free text and audio.",
  },
];
