/* PlotPoint — the title collection (single source of truth for the hub).
   Each title is a standalone learning room. status: "live" (has href) or
   "planned" (coming soon, no link yet). Flip status + set href when a room ships.

   English base lives here; per-language card overrides (title stays in its
   published form; genre/desc/tags translate) live in plotpoint-i18n.js under
   __PLOTPOINT_TITLES__. Filter facet values below are STABLE KEYS — the hub
   translates them for display via the chrome dictionary (facet.* keys). */
window.PLOTPOINT_TITLES = [
  {
    id: "metamorphosis",
    title: "The Metamorphosis",
    author: "Franz Kafka",
    href: "metamorphosis/",
    status: "live",
    accent: "#7a4fce",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "novella"],
    time: "60-90",
    reading: ["after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "Gregor's Room",
    ctob: "The Locked Door",
    arcade: "Routine Breakdown",
    desc: "Gregor Samsa wakes transformed. Investigate obligation, isolation, and identity through symbols, evidence, and the pressures of a changing family.",
  },
  {
    id: "myths",
    title: "Selected Myths (Bulfinch)",
    author: "Thomas Bulfinch",
    status: "planned",
    accent: "#c9822b",
    grades: "6–9",
    gradeBand: "6-8",
    genre: ["mythology", "nonfiction"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["multi", "relational"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "not-required",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Museum of Lost Myths",
    ctob: "Who Stole the Fire?",
    arcade: "Hero's Path",
    desc: "Gods, quests, and archetypes. Match obstacles to transformations, recognize quest patterns, and transfer myth patterns to modern stories.",
  },
  {
    id: "giver",
    title: "The Giver",
    author: "Lois Lowry",
    status: "planned",
    accent: "#3f7f8c",
    grades: "7–9",
    gradeBand: "6-8",
    genre: ["fiction", "dystopian"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Memory Vault",
    ctob: "The Missing Memory",
    arcade: "Memory Runner",
    desc: "Distinguish freedom, safety, conformity, memory, choice, and responsibility in a community that traded feeling for order.",
  },
  {
    id: "orient",
    title: "Murder on the Orient Express",
    author: "Agatha Christie",
    status: "planned",
    accent: "#8c3f52",
    grades: "7–10",
    gradeBand: "6-8",
    genre: ["fiction", "mystery"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Evidence Carriage",
    ctob: "The Locked Compartment",
    arcade: "Timeline Switchboard",
    desc: "Sequence statements, identify contradictions, test reliability, separate clue from assumption, and build an evidence-supported verdict.",
  },
  {
    id: "mango",
    title: "The House on Mango Street",
    author: "Sandra Cisneros",
    status: "planned",
    accent: "#c25b2e",
    grades: "8–10",
    gradeBand: "9-12",
    genre: ["fiction", "coming-of-age"],
    time: "30-45",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["multi", "relational"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "Esperanza's Neighborhood",
    ctob: "The Missing Vignette",
    arcade: "Mango Street Mapper",
    desc: "Connect place and identity, recognize symbols, analyze changing perceptions, and match voice to experience.",
  },
  {
    id: "martian",
    title: "The Martian Chronicles",
    author: "Ray Bradbury",
    status: "planned",
    accent: "#a8432b",
    grades: "8–10",
    gradeBand: "9-12",
    genre: ["fiction", "science-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Abandoned Colony",
    ctob: "The Last Transmission",
    arcade: "Mars Signal",
    desc: "Distinguish fact, rumor, fear, cultural assumption, and reliable evidence across conflicting accounts of a new world.",
  },
  {
    id: "maus",
    title: "Maus I",
    author: "Art Spiegelman",
    status: "planned",
    accent: "#4a5568",
    grades: "8–10",
    gradeBand: "9-12",
    genre: ["nonfiction", "graphic-novel", "memoir"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Archive Box",
    ctob: "The Broken Testimony",
    arcade: "Panel Detective",
    desc: "Analyze sequence, connect visual choices to meaning, examine caption–image relationships, and distinguish memory from documentation. Content and copyright review required.",
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    status: "planned",
    accent: "#6b2a3a",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "gothic", "horror"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Demeter Archive",
    ctob: "The Missing Ship Log",
    arcade: "Night Route",
    desc: "Reconstruct movement, sequence documents, evaluate narrators, connect setting and suspense, and analyze epistolary structure.",
  },
  {
    id: "butterflies",
    title: "In the Time of the Butterflies",
    author: "Julia Alvarez",
    status: "planned",
    accent: "#8c5a2b",
    grades: "9–12",
    gradeBand: "9-12",
    genre: ["fiction", "historical-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Hidden Resistance Cache",
    ctob: "Code of the Butterflies",
    arcade: "Clandestine Courier",
    desc: "Analyze risk, compare perspectives, identify motivation, connect historical context, and evaluate resistance decisions.",
  },
  {
    id: "kindred",
    title: "Kindred",
    author: "Octavia E. Butler",
    status: "planned",
    accent: "#5c4a7a",
    grades: "10–12",
    gradeBand: "9-12",
    genre: ["fiction", "historical-fiction", "science-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Family Archive",
    ctob: "The Broken Ledger",
    arcade: "Timeline Repair",
    desc: "Reconstruct chronology, analyze cause and effect, compare historical and fictional evidence, and examine perspective across time.",
  },
  {
    id: "bnw",
    title: "Brave New World",
    author: "Aldous Huxley",
    status: "planned",
    accent: "#2f6f7a",
    grades: "10–12",
    gradeBand: "9-12",
    genre: ["fiction", "dystopian", "science-fiction"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "partial",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The World State Systems Lab",
    ctob: "The Forbidden Book",
    arcade: "Slogan Scramble",
    desc: "Identify propaganda, analyze euphemism, recognize manipulation, compare social-control systems, and separate slogan from supported claim.",
  },
  {
    id: "justmercy",
    title: "Just Mercy",
    author: "Bryan Stevenson",
    status: "planned",
    accent: "#3f6b4a",
    grades: "10–12",
    gradeBand: "9-12",
    genre: ["nonfiction", "memoir"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "copyrighted",
    grouping: ["individual", "group"],
    genai: "optional",
    printable: true,
    relicRoom: "The Appeals Case File",
    ctob: "The Missing Evidence",
    arcade: "Claim or Proof",
    desc: "Sort claims, evidence, assumptions, allegations, conclusions, and counterclaims through rhetorical analysis and argument mapping.",
  },
  {
    id: "canterbury",
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    href: "canterbury/",
    status: "live",
    accent: "#8c6a2b",
    grades: "11–12",
    gradeBand: "9-12",
    genre: ["fiction", "poetry", "classic"],
    time: "60-90",
    reading: ["during", "after"],
    ace: ["articulate", "connect", "extend"],
    solo: ["relational", "extended"],
    activities: ["vocab", "relic", "ctob", "arcade", "analysis", "extend", "print"],
    spoiler: "none",
    fulltext: "recommended",
    rights: "public-domain",
    grouping: ["individual", "partner"],
    genai: "optional",
    printable: true,
    relicRoom: "The Pilgrims' Luggage",
    ctob: "The Missing Tale",
    arcade: "Pilgrim Road",
    desc: "Match traveler and object, analyze motivation, identify satire, interpret social roles, and connect frame story and tale.",
  },
];
